/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignments_java;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author assud
 */
public class Assignment4 extends javax.swing.JFrame {

    String message = "Color mixer GUI Application";
    ImageIcon icon;
    public Assignment4() {
        initComponents();
        icon = new ImageIcon("C:/Users/assud/Desktop/SCA JAva/microsoft-paint.png");
        setIconImage(icon.getImage());
        setTitle(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CboxRed = new javax.swing.JCheckBox();
        CboxGreen = new javax.swing.JCheckBox();
        CboxBlue = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CboxRed.setText("Red");
        CboxRed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CboxRedItemStateChanged(evt);
            }
        });

        CboxGreen.setText("Green");
        CboxGreen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CboxGreenItemStateChanged(evt);
            }
        });

        CboxBlue.setText("Blue");
        CboxBlue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CboxBlueItemStateChanged(evt);
            }
        });
        CboxBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxBlueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Background Color Mixer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(CboxRed, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(CboxGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(CboxBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxRed, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboxBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxBlueActionPerformed
        
    }//GEN-LAST:event_CboxBlueActionPerformed

    private void CboxRedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CboxRedItemStateChanged
        if(CboxRed.isSelected()==true&& CboxBlue.isSelected()==false && CboxGreen.isSelected()==false)
        {
            jPanel1.setBackground(Color.red);
        }
        if(CboxRed.isSelected()==true && CboxBlue.isSelected()==true&& CboxGreen.isSelected()==true){
            jPanel1.setBackground(Color.white);
        }
        else if(CboxBlue.isSelected()==true&& CboxRed.isSelected()==true){
            jPanel1.setBackground(Color.MAGENTA);
        }
        else if(CboxGreen.isSelected()==true&& CboxRed.isSelected()==true){
            jPanel1.setBackground(Color.yellow);
        }
        else
        {
            jPanel1.setBackground(Color.black);
        }
    }//GEN-LAST:event_CboxRedItemStateChanged

    private void CboxGreenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CboxGreenItemStateChanged
       if(CboxGreen.isSelected()==true && CboxBlue.isSelected()==false && CboxRed.isSelected()==false)
        {
            jPanel1.setBackground(Color.green);
        }
       if(CboxRed.isSelected()==true && CboxBlue.isSelected()==true&& CboxGreen.isSelected()==true){
            jPanel1.setBackground(Color.white);
        }
        else if(CboxGreen.isSelected()==true&& CboxRed.isSelected()==true){
            jPanel1.setBackground(Color.yellow);
        }
        else if(CboxBlue.isSelected()==true&& CboxGreen.isSelected()==true){
            jPanel1.setBackground(Color.cyan);
        }
        else
        {
            jPanel1.setBackground(Color.black);
        }
    }//GEN-LAST:event_CboxGreenItemStateChanged

    private void CboxBlueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CboxBlueItemStateChanged
        if(CboxBlue.isSelected()==true && CboxRed.isSelected()==false && CboxGreen.isSelected()==false)
        {
            jPanel1.setBackground(Color.blue);
        }
        if(CboxRed.isSelected()==true && CboxBlue.isSelected()==true&& CboxGreen.isSelected()==true){
            jPanel1.setBackground(Color.white);
        }
        else if(CboxBlue.isSelected()==true&& CboxRed.isSelected()==true){
            jPanel1.setBackground(Color.MAGENTA);
        }
        else if(CboxBlue.isSelected()==true&& CboxGreen.isSelected()==true){
            jPanel1.setBackground(Color.cyan);
        }
        else
        {
            jPanel1.setBackground(Color.black);
        }
    }//GEN-LAST:event_CboxBlueItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CboxBlue;
    private javax.swing.JCheckBox CboxGreen;
    private javax.swing.JCheckBox CboxRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
